<?php
use PWA\pwaction;
?>
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <!-- manifest="/templates/AdminLTE-2.3.7/template.appcache" -->
    <!-- <link rel="manifest" href="/manifest.json"> -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PWA template</title>

    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"> -->
    <link rel="stylesheet" href="templates/uni/css/bootstrap.min.css">
    <link rel="stylesheet" href="templates/uni/css/font-awesome.min.css">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div id="worker">
      <div id="print">inicio</div>
      <div class="" id="stop"></div>
      <button type="button" id="startWorker" >startWorker</button>
      <hr>
    </div>
    <div id="localStorage">
      <input type="text" id="localStorageInput" name="" value=""><br>
      <button type="button" name="button" id="setLocalStorage" autofocus>setLocalStorage</button>
      <button type="button" name="button" id="getLocalStorage">getLocalStorage</button><br>
      <input type="text" id="resp_local" name="" value=""><br>
    </div>
<hr>
    <div id="sessionStorage">
      <input type="text" id="sessionStorageInput" name="" value=""><br>
      <button type="button" name="button" id="setSessionStorage">setSessionStorage</button>
      <button type="button" name="button" id="getSessionStorage">getSessionStorage</button><br>
      <input type="text" id="resp_session" name="" value="">
    </div>
  <hr>
  </body>
  <script type="text/javascript">
    // document.body.onload();
  </script>
  <script src="templates/uni/js/jquery.min.js"></script>
  <script src="templates/uni/js/bootstrap.min.js"></script>
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script> -->
  <script src="pwaction/pwaction.js" charset="utf-8"></script>
  <script src="pwaction/pwaux.js" charset="utf-8"></script>
  <script src="pwaction/pws.js" charset="utf-8"></script>
  <script src="templates/uni/js/scripts.js" charset="utf-8"></script>
  <!-- <script type="text/javascript">
    if('serviceWorker' in navigator) {
      navigator.serviceWorker.register('/sw.js', { scope: '/' })
        .then(function(registration) {
              console.log('Service Worker Registered! Scope is ' + registration.scope);
        });
      navigator.serviceWorker.ready.then(function(registration) {
         console.log('Service Worker Ready');
      });
    }
  </script> -->
</html>
