<html>

	<div id='conteudo'>
		<section class='col-lg-6 col-md-6 connectedSortable ui-sortable' id='mod'>
			<div class='box box-success' id='box'>
				<div id='box-header' class='box-header with-border'>
				<h3 id='box-title' class='box-title'></h3>

				<div id='box-tools' class='box-tools pull-right'>
					<span id='label' class='label label-primary'></span>
				</div>

				</div>
				<div id='box-body' class='box-body'>

				</div>
				<div id='box-footer' class='box-footer'>

				</div>
			</div>
		</section>
	</div>

</html>
