<!DOCTYPE html>
<html>
  <div id='conteudo'>

    <section class='col-lg-6 col-md-6 connectedSortable ui-sortable' id='mod'>
    <div class="box box-danger">
      <div class="box-header with-border">
        <h3 class="box-title" id="box-title">Latest Members</h3>

        <div class="box-tools id="box-tools" pull-right">
          <span class="label label-danger">8 New Members</span>
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
          </button>
          <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
          </button>
        </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body id="box-body" no-padding">

      </div>
      <!-- /.box-body -->
      <div class="box-footer id="box-footer" text-center">
        <a href="javascript:void(0)" class="uppercase">View All Users</a>
      </div>
      <!-- /.box-footer -->
    </div>
    <!--/.box -->
  </section>
  
  </div>
</html>
