<html>

	<div id='conteudo'>

		<section class='col-xs-12'>
			<div class='box box-solid box-primary'>
				<div class='box-header' id='box-header'>
					<h3 class='box-title' id='box-title'></h3>
				</div>
				<!-- /.box-header -->
				<div class='box-body' id='box-body'>

					<table id='example1' class='table table-bordered table-striped' style='text-align:left'>
						<thead>
						<tr>
							<th>Rota</th>
							<th>Escopo</th>
							<th>Categorias</th>
						</tr>
						</thead>
						<tbody id='table-body'>
						</tbody>
						<tfoot>
						<tr>
							<th>Rota</th>
							<th>Escopo</th>
							<th>Categorias</th>

						</tr>
						</tfoot>
					</table>
				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->
		</section>
	</div><!-- /#conteudo -->
</html>
