<!DOCTYPE html>
<html>
  <div id="conteudo">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image" id='logeduserimage'>
          <img src="/templates/AdminLTE-2.3.7/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info" id='logeduserinfo'>
          <p class='logedusername'> </p>
          <span class='logedusercargo'><i class="fa fa-circle text-success"></i> </span><br>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->

      <div id="ws-only-menu">

      </div>

    </section>
    <!-- /.sidebar -->
  </div>
</html>
