<html>
  <div id='conteudo'>
    <div class='col-xs-12'>
      <div class='box box-solid box-primary'>
        <div class='box-header'>
          <h3 class='box-title'>{$tituloModulo}</h3>
        </div>
        <!-- /.box-header -->
        <div class='box-body'>
          <table id='example1' class='table table-bordered table-striped' style='text-align:left'>
            <thead>
            <tr>
      <th>Nome</th>
              <th>E-mail</th>
              <th>CPF</th>
            </tr>
            </thead>
            <tbody>
            {$conteudoBody}
            </tbody>
            <tfoot>
            <tr>
              <th>Nome</th>
              <th>E-mail</th>
              <th>CPF</th>
            </tr>
            </tfoot>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
  </div><!-- /#conteudo -->
</html>
