<html>
		<div id='conteudo'>
			<section class='col-sm-12 col-lg-12 col-md-12 col-xs-12 table-responsive connectedSortable ui-sortable'>
					<div id='box-warning'>
						<!-- {$display['warning']} -->
					</div>
					<div class='box box-success' id='box'>
						<div id='box-header' class='box-header with-border'>
						<h3 id='box-title' class='box-title'>

						<!-- {$display['conteudoHeader']} -->

						</h3>
						<div id='box-tools' class='box-tools pull-right'>
							<div id='label_up_licencas'>
								<span id='label_licencas' class='label label-primary'>! ! !</span>
							</div>
						</div>

						</div>
						<div id='box-body' class='box-body'>

						<!-- {$display['conteudoBody']} -->

						</div>
						<div id='box-footer' class='box-footer'>

						<!-- {$display['rodape']} -->

						</div>
					</div>
				</section>
		</div><!-- /#conteudo -->
	</html>
