<!DOCTYPE html>
<html>
  <div id="conteudo">
    <section class='sidebar' style='height: auto;'>
      <!-- Sidebar user panel -->
      <div id='user-panel'>

      </div>
      <!-- search form -->
      <div id='sidebar-form'>

      </div>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <div id="ws-only-menu-div">
        <ul class='sidebar-menu' id="ws-menu">

        </ul>
      </div>
    </section>
  </div>
</html>
