<!DOCTYPE html>
<html >
  <div id="conteudo">
    <li class='treeview'>
      <a class='menulink' href='#' title="testando!!">
        <i class='fa fa-dashboard'></i>
        <span id="menuname"> HERRE </span>
        <span class='pull-right-container'>
          <i class='fa fa-angle-left pull-right'></i>
        </span>
      </a>
    </li>
  <!-- aqui irão os menus -->
<!-- caso necessário aqui irão os sub menus -->
<!-- <ul class='treeview-menu' style='display: none;'>
<li><a href='index1.html'><i class='fa fa-circle-o'></i> Dashboard v1</a></li>
<li><a href='index2.html'><i class='fa fa-circle-o'></i> Dashboard v2</a></li>
</ul> -->

  </div>
</html>
