<!DOCTYPE html>
<html lang="pt-br">
<head>
  <!-- manifest="template.php" -->
  <!-- manifest="/templates/AdminLTE-2.3.7/template.appcache" -->
  <!-- <link rel="manifest" href="/manifest.json"> -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Secretaria de Meio Ambiente</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="/templates/AdminLTE-2.3.7/bootstrap/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/templates/AdminLTE-2.3.7/css/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="/templates/AdminLTE-2.3.7/css/ionicons-2.0.1.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/templates/AdminLTE-2.3.7/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="/templates/AdminLTE-2.3.7/dist/css/skins/_all-skins.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="/templates/AdminLTE-2.3.7/plugins/iCheck/flat/blue.css">
  <!-- Morris chart -->
  <link rel="stylesheet" href="/templates/AdminLTE-2.3.7/plugins/morris/morris.css">
  <!-- jvectormap -->
  <link rel="stylesheet" href="/templates/AdminLTE-2.3.7/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
  <!-- Date Picker -->
  <link rel="stylesheet" href="/templates/AdminLTE-2.3.7/plugins/datepicker/datepicker3.css">
	<!-- Data Table -->
  <link rel="stylesheet" href="/templates/AdminLTE-2.3.7/plugins/datatables/dataTables.bootstrap.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="/templates/AdminLTE-2.3.7/plugins/daterangepicker/daterangepicker.css">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="/templates/AdminLTE-2.3.7/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
  <!-- <style media="screen">
      /* Start by setting display:none to make this hidden.
     Then we position it in relation to the viewport window
     with position:fixed. Width, height, top and left speak
     speak for themselves. Background we set to 80% white with
     our animation centered, and no-repeating */
    .modal {
      display:    none;
      position:   fixed;
      z-index:    1000;
      top:        0;
      left:       0;
      height:     100%;
      width:      100%;
      background: rgba( 255, 255, 255, .8 )
                  url('http://sampsonresume.com/labs/pIkfp.gif')
                  50% 50%
                  no-repeat;
    }
    /* When the body has the loading class, we turn
     the scrollbar off with overflow:hidden */
    body.loading {
      overflow: hidden;
    }

    /* Anytime the body has the loading class, our
     modal element will be visible */
    body.loading .modal {
      display: block;
    }
  </style> -->

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
  <header class="main-header">
    <!-- Logo -->
    <a href="./" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->

          <!-- Notifications: style can be found in dropdown.less -->

          <!-- Tasks: style can be found in dropdown.less -->

          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="/templates/AdminLTE-2.3.7/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
              <span class="hidden-xs"></span> <span class="logedusername"></span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="/templates/AdminLTE-2.3.7/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                <p class='logedusername'>

                </p>
								<p class='logeduserpro'></p>
              </li>
              <!-- Menu Body -->
              <!--
							<li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div>

              </li>
							-->
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Perfil</a>
                </div>
                <div class="pull-right">
                  <a href="./?logout=true" class="btn btn-default btn-flat">SAIR</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <div id="sidebar-menu">
    </div>
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        UNI
        <small>Sistema de Gestão Pública</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-flag-o"></i> UNI</a></li>
        <li class="active">SIGMA</li>
		<li class="active">Licam</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content" id="content">
				<!-- CONTEÚDO AQUI, VER DOCUMENTAÇÃO -->
				<!--conteúdo inicial -->
			<div class='row' id='unicontentrow1'>

			</div>
			<div class='row' id='unicontentrow2'>

			</div>
			<div class='row' id='unicontentrow3'>

			</div>
			<div class='row' id='unicontentrow4'>

			</div>
			<div class='row' id='unicontentrow5'>

			</div>


    </section>
    <!-- /.content -->

    <!-- Modal spaces -->
    <section class="content" id="content">
      <div class='row' id='modalcontentrow'>

			</div>
    </section>
    <!-- /.Modal -->

  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version: </b> UNI 1.0.12
        <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Licença Creative Commons" style="border-width:0" src="/templates/AdminLTE-2.3.7/imgs/88x31.png" /></a><br />.
    </div>
    <strong>Copyright &copy; 2016-2017 <a href="http://websailor.com.br"> Websailor &reg; </a> . </strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-user bg-yellow"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                <p>New phone +1(800)555-1234</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                <p>nora@example.com</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-file-code-o bg-green"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                <p>Execution time 5 seconds</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="label label-danger pull-right">70%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Update Resume
                <span class="label label-success pull-right">95%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-success" style="width: 95%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Laravel Integration
                <span class="label label-warning pull-right">50%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Back End Framework
                <span class="label label-primary pull-right">68%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Allow mail redirect
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Other sets of options are available
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Expose author name in posts
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Allow the user to show his name in blog posts
            </p>
          </div>
          <!-- /.form-group -->

          <h3 class="control-sidebar-heading">Chat Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Show me as online
              <input type="checkbox" class="pull-right" checked>
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Turn off notifications
              <input type="checkbox" class="pull-right">
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Delete chat history
              <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
            </label>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery 3.1.1 -->
<!-- <script src="templates/AdminLTE-2.3.7/js/jquery-3.1.1.min.js"></script> -->
<!-- jQuery 2.2.3 -->
<!-- <script src="/templates/AdminLTE-2.3.7/plugins/jQuery/jquery-2.2.3.min.js"></script> -->
<script src="/templates/AdminLTE-2.3.7/js/jquery-2.2.3.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="/templates/AdminLTE-2.3.7/js/jquery-ui-1.11.4.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!--  P-W-A-C-T-I-O-N  0.1.6 -->
<script src="/templates/AdminLTE-2.3.7/pwaction/pwaction.js"></script>
<script src="/templates/AdminLTE-2.3.7/pwaction/pwaux.js"></script>
<script src="/templates/AdminLTE-2.3.7/pwaction/pws.js"></script>
<script src="/templates/AdminLTE-2.3.7/pwaction/scripts.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="/templates/AdminLTE-2.3.7/bootstrap/js/bootstrap.min.js"></script>
<!-- DataTables -->
<script src="/templates/AdminLTE-2.3.7/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/templates/AdminLTE-2.3.7/plugins/datatables/dataTables.bootstrap.min.js"></script>
<!-- Morris.js charts -->
<script src="/templates/AdminLTE-2.3.7/js/raphael-2.1.0.min.js"></script>
<script src="/templates/AdminLTE-2.3.7/plugins/morris/morris.min.js"></script>
<!-- Sparkline -->
<script src="/templates/AdminLTE-2.3.7/plugins/sparkline/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="/templates/AdminLTE-2.3.7/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="/templates/AdminLTE-2.3.7/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- jQuery Knob Chart -->
<script src="/templates/AdminLTE-2.3.7/plugins/knob/jquery.knob.js"></script>
<!-- daterangepicker -->
<script src="/templates/AdminLTE-2.3.7/js/moment-2.11.2.min.js"></script>
<script src="/templates/AdminLTE-2.3.7/plugins/daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="/templates/AdminLTE-2.3.7/plugins/datepicker/bootstrap-datepicker.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="/templates/AdminLTE-2.3.7/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<!-- Slimscroll -->
<script src="/templates/AdminLTE-2.3.7/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/templates/AdminLTE-2.3.7/plugins/fastclick/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/templates/AdminLTE-2.3.7/dist/js/app.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<!-- <script src="/templates/AdminLTE-2.3.7/dist/js/pages/dashboard.js"></script> -->
<!-- AdminLTE for demo purposes -->
<script src="/templates/AdminLTE-2.3.7/dist/js/demo.js"></script>
<!-- page script -->
<script>
	$(document).ready(function(){
		// $('#example1').DataTable();
		$('#example1').DataTable();
		// $('#example2').DataTable({
		  // "paging": true,
		  // "lengthChange": false,
		  // "searching": false,
		  // "ordering": true,
		  // "info": true,
		  // "autoWidth": false
		// });
	});
</script>
<script src="http://mvcframework.dev/templates/AdminLTE-2.3.7/js/uni_tool.js"></script>


</body>
</html>
